In [47]:
source("../src/utils/nuevo_regimen.R")
mujeres <- read.csv("../data/input/mujeres.csv")

In [48]:
nuevo_regimen(mujeres, 57, 0.0788, 0.03, 0.132, 1423500, 1423500, 25, 2.3)

[1] 925275

In [51]:
# Parámetros constantes
  tabla_mortalidad <- mujeres
  r <- 0.0788
  e <- 0.03
  tc <- 0.132
  Sm <- 1423500
  h <- 2.3

  # Valores variables
  x_values <- c(57, 62, 67)
  n_values <- c(25, 35, 42)
  S_values <- 1:25 * 1423500

  # Función para crear una tabla para un valor específico de x
  crear_tabla <- function(x_val) {
    # Crear matriz para almacenar resultados
    resultados <- matrix(NA, nrow = 25, ncol = 3)
    colnames(resultados) <- paste(n_values, "años")

    # Llenar la matriz
    for(i in 1:25) {
      S <- S_values[i]
      for(j in 1:3) {
        n <- n_values[j]
        resultados[i, j] <- nuevo_regimen(tabla_mortalidad, x_val, r, e, tc, Sm, S, n, h)
      }
    }

    # Crear data frame con formato
    df <- data.frame(
      SMMLV = 1:25,
      resultados
    )

    # Formatear números a pesos colombianos
    for(col in 2:4) {
      df[, col] <- format(round(df[, col]), big.mark = ",", scientific = FALSE)
    }

    return(df)
  }

  # Crear las tres tablas
  tabla_x57 <- crear_tabla(57)
  tabla_x62 <- crear_tabla(62)
  tabla_x67 <- crear_tabla(67)

  # Mostrar las tablas con formato
  cat("╔══════════════════════════════════════════════════════════════╗\n")
  cat("║                MESADA PENSIONAL - EDAD 57 AÑOS               ║\n")
  cat("╚══════════════════════════════════════════════════════════════╝\n\n")
  print(tabla_x57, row.names = FALSE)

  cat("\n\n╔══════════════════════════════════════════════════════════════╗\n")
  cat("║                MESADA PENSIONAL - EDAD 62 AÑOS               ║\n")
  cat("╚══════════════════════════════════════════════════════════════╝\n\n")
  print(tabla_x62, row.names = FALSE)

  cat("\n\n╔══════════════════════════════════════════════════════════════╗\n")
  cat("║                MESADA PENSIONAL - EDAD 67 AÑOS               ║\n")
  cat("╚══════════════════════════════════════════════════════════════╝\n\n")
  print(tabla_x67, row.names = FALSE)

╔══════════════════════════════════════════════════════════════╗
║                MESADA PENSIONAL - EDAD 57 AÑOS               ║
╚══════════════════════════════════════════════════════════════╝

 SMMLV   X25.años   X35.años   X42.años
     1    925,275  1,138,800  1,138,800
     2  1,836,315  2,263,365  2,263,365
     3  2,361,942  3,020,987  3,171,841
     4  2,726,357  3,625,313  3,991,673
     5  3,090,771  4,229,639  4,811,505
     6  3,455,186  4,833,965  5,631,338
     7  3,819,601  5,438,291  6,451,170
     8  4,184,016  6,042,617  7,271,002
     9  4,548,431  6,646,943  8,090,834
    10  4,912,846  7,251,270  8,910,666
    11  5,277,261  7,855,596  9,730,498
    12  5,641,676  8,459,922 10,550,330
    13  6,006,091  9,064,248 11,370,163
    14  6,370,506  9,668,574 12,189,995
    15  6,734,921 10,272,900 13,009,827
    16  7,099,336 10,877,226 13,829,659
    17  7,463,751 11,481,552 14,649,491
    18  7,828,165 12,085,878 15,469,323
    19  8,192,580 12,690,204 16,289,155
    20  8,556,995 13,294,531 17,108,988
    21  8,921,410 13,898,857 17,928,820
    22  9,285,825 14,503,183 18,748,652
    23  9,650,240 15,107,509 19,568,484
    24 10,014,655 15,711,835 20,388,316
    25 10,379,070 16,316,161 21,208,148


╔══════════════════════════════════════════════════════════════╗
║                MESADA PENSIONAL - EDAD 62 AÑOS               ║
╚══════════════════════════════════════════════════════════════╝

 SMMLV   X25.años   X35.años   X42.años
     1    925,275  1,138,800  1,138,800
     2  1,836,315  2,263,365  2,263,365
     3  2,391,290  3,069,657  3,237,868
     4  2,797,632  3,743,513  4,152,023
     5  3,203,974  4,417,368  5,066,179
     6  3,610,315  5,091,223  5,980,335
     7  4,016,657  5,765,078  6,894,491
     8  4,422,999  6,438,933  7,808,646
     9  4,829,341  7,112,789  8,722,802
    10  5,235,682  7,786,644  9,636,958
    11  5,642,024  8,460,499 10,551,113
    12  6,048,366  9,134,354 11,465,269
    13  6,454,707  9,808,209 12,379,425
    14  6,861,049 10,482,065 13,293,581
    15  7,267,391 11,155,920 14,207,736
    16  7,673,732 11,829,775 15,121,892
    17  8,080,074 12,503,630 16,036,048
    18  8,486,416 13,177,485 16,950,203
    19  8,892,757 13,851,341 17,864,359
    20  9,299,099 14,525,196 18,778,515
    21  9,705,441 15,199,051 19,692,670
    22 10,111,783 15,872,906 20,606,826
    23 10,518,124 16,546,761 21,520,982
    24 10,924,466 17,220,617 22,435,138
    25 11,330,808 17,894,472 23,349,293


╔══════════════════════════════════════════════════════════════╗
║                MESADA PENSIONAL - EDAD 67 AÑOS               ║
╚══════════════════════════════════════════════════════════════╝

 SMMLV   X25.años   X35.años   X42.años
     1    925,275  1,138,800  1,138,800
     2  1,836,315  2,263,365  2,263,365
     3  2,431,557  3,136,434  3,328,457
     4  2,895,424  3,905,685  4,372,027
     5  3,359,290  4,674,935  5,415,597
     6  3,823,156  5,444,186  6,459,166
     7  4,287,022  6,213,437  7,502,736
     8  4,750,888  6,982,687  8,546,306
     9  5,214,754  7,751,938  9,589,875
    10  5,678,620  8,521,188 10,633,445
    11  6,142,486  9,290,439 11,677,015
    12  6,606,353 10,059,690 12,720,584
    13  7,070,219 10,828,940 13,764,154
    14  7,534,085 11,598,191 14,807,724
    15  7,997,951 12,367,441 15,851,293
    16  8,461,817 13,136,692 16,894,863
    17  8,925,683 13,905,943 17,938,433
    18  9,389,549 14,675,193 18,982,002
    19  9,853,415 15,444,444 20,025,572
    20 10,317,281 16,213,694 21,069,141
    21 10,781,148 16,982,945 22,112,711
    22 11,245,014 17,752,196 23,156,281
    23 11,708,880 18,521,446 24,199,850
    24 12,172,746 19,290,697 25,243,420
    25 12,636,612 20,059,947 26,286,990